import React from "react";
import Head from 'next/head'
import Footer from "./Footer/Footer";
import Header from "./Header/Header";

const Layout = ({ children }) => {
    return (
        <>
            <Head>
                <title>Voting system</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main className="p-4 bg-gradient-to-bl from-purple-800 to-blue-700 bg-no-repeat">
                {children}
            </main>
            <Footer />
        </>
    )
}

export default Layout;