import Head from 'next/head'

import {
  Button,
} from "@material-tailwind/react";

export default function Home() {
  return (
    <div >
      <Head>
        <title>Voting system</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Button>Vote</Button>
      </main>
    </div>
  )
}
