import Head from 'next/head'
import Candidate from '../components/Candidate';
import { Typography } from "@material-tailwind/react";

import candidates from '../data/candidates.json';


export default function Home() {

  return (
    <>
      <Head>
        <title>Voting system</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-4 bg-gradient-to-bl from-purple-800 to-blue-700 bg-no-repeat">
        <Typography variant="h1" color="white" className="text-center my-5">Election 2022</Typography>
        <p className="text-center text-white my-5">Choose your preferred candidate:</p>
        <div className="max-w-screen-md mx-auto my-5">
          <div className="grid grid-cols-2 gap-4">
            {
              candidates.map((candidate) => <Candidate key={candidate.id} candidate={candidate}></Candidate>)
            }
          </div>
        </div>
      </main>
    </>
  )
}
